# ==============
# --- Config ---
# ==============

# model
MODEL_NAME = "t5-small"
MAX_LENGTH = 32

# test_anagram
BEAM_SIZE = 647
SEARCH_TIME_LIMIT = 20
MIN_ANAGRAMS = 100
STOP_GROUP_AFTER_MIN_FOUND = True
MIN_NON_EMPTY_GROUPS = 5
HUMAN_IN_THE_LOOP = False
ASK_USER_FOR_FAVORITE = True
JUST_MEASURING_SEARCH_DURATION = False
